---
# tasks file for hadoop-common
# If the group zookeeper exists and is populated, we will assume this will be 
# an HA deployment.  We perhaps need a better way to determine if HA will be 
# configured, but this should work for the time being.
- block:
  - name: get configured zookeeper client port
    shell: grep clientPort /etc/zookeeper/zoo.cfg | cut -f2 -d"="
    delegate_to: "{{ groups['zookeeper'] }}"
    run_once: true
    register: zk_client_port

  - name: set zookeeper client port value
    set_fact:
      hadoop_zk_client_port: "{{ zk_client_port.stdout }}"
  when: ( groups['zookeeper'] is defined ) and ( groups['zookeeper'] | length > 0)

- name: copy out sh env file
  template:
    src: hadoop.sh.j2
    dest: /etc/profile.d/hadoop.sh
    owner: root
    group: root
    mode: 0644

- name: install base hadoop
  yum:
    name: hadoop
    state: present

- name: install mapreduce
  yum:
    name: hadoop-mapreduce
    state: present

- name: copy out core-site.xml template
  template:
    src: core-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/core-site.xml"
    owner: root
    group: root
    mode: 0644

- name: copy out yarn-site.xml template
  template:
    src: yarn-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/yarn-site.xml"
    owner: root
    group: root
    mode: 0644

- name: copy out mapred-site.xml template
  template:
    src: mapred-site.xml.j2
    dest: "{{ hadoop_conf_dir }}/mapred-site.xml"
    owner: root
    group: root
    mode: 0644

- name: copy out hadoop environment template
  template:
    src: hadoop-env.sh.j2
    dest: "{{ hadoop_conf_dir }}/hadoop-env.sh"
    owner: root
    group: root
    mode: 0644

- name: copy out yarn environment template
  template:
    src: yarn-env.sh.j2
    dest: "{{ hadoop_conf_dir }}/yarn-env.sh"
    owner: root
    group: root
    mode: 0644

- name: copy out node inclusion/exclusion lists for YARN
  template:
    src: "{{ item }}.j2"
    dest: "{{ hadoop_conf_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - yarn.include
    - yarn.exclude

- name: copy out hadoop daemon configuration file (defaults)
  template:
    src: etc-default-hadoop.j2
    dest: /etc/default/hadoop
    owner: root
    group: root
    mode: 0644

- name: create custom facts directory
  file:
    name: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root

